### ISSUE TITLE
error on "conan install .."

### ISSUE THREAD

**Issue by Harish765** [systelab/cpp-rest-api-core#1]
ERROR: Failed requirement 'WebServerAdapterInterface/1.1.2@systelab/stable' from 'conanfile.py (RESTAPICore/None)'
ERROR: Unable to find 'WebServerAdapterInterface/1.1.2@systelab/stable' in remotes
[](url)

**Comment by joaquimvila** [comment]
Updated documentation to properly describe how to install or build this library using Conan.
The problem you were encountering is that you need to configure a remote conan repository to required dependencies. Execute the following command to do so:
```cmd
conan remote add systelab-bintray https://api.bintray.com/conan/systelab/conan
```
